import mongoose from "mongoose"
const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        require:true,
        min:3,
        max:20,
        unique:true
    },
    email:{
        type:String,
        require:true,
        max:50,
        unique:true
    },
    password:{
        type:String,
        require:true,
        min:6
    },
    profilePicture:{
        type:String,
        default:"https://imgs.search.brave.com/dtS9dreVLOOHIfbuSOokrJ1xtgBu2Vk8Kf4R6forAhI/rs:fit:250:250:1/g:ce/aHR0cHM6Ly93d3cu/cGVyc29uYWxpdHkt/aW5zaWdodHMuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE3/LzEyL2RlZmF1bHQt/cHJvZmlsZS1waWMt/ZTE1MTMyOTE0MTA1/MDUuanBn"
    },
    coverPicture:{
        type:String,
        default:"https://imgs.search.brave.com/k5WJxIcOoG0jdVWic-SiFBMtFp2ZEAqHTIquPGJJmso/rs:fit:1124:366:1/g:ce/aHR0cHM6Ly93d3cu/ZmlsZXBpY2tlci5p/by9hcGkvZmlsZS8y/bmtibEpsUU1LemNN/M0Vta1lBVg"
    },
    followers:{
        type:Array,
        default:[]
    },
    followings:{
        type:Array,
        default:[]
    },
    notifications:{
        type:Array,
        default:[]
    },
    messages:{
        type:Array,
        default:[]
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    isStudent:{
        type:Boolean,
        default:false
    },
    isAdvisor:{
        type:Boolean,
        default:false
    },
    isExpert:{
        type:Boolean,
        default:false
    },
    blockStatus:{
        type:Boolean,
        default:false
    },
    desc:{
        type:String,
        max:100
    },
    city:{
        type:String,
        max:50
    },
    from:{
        type:String,
        max:100
    },
    address:{
        type:String,
        max:100
    },
    relationship:{
        type:Number,
        enum:[1,2,3]
    },
    education:{
        type:Array,
        default:[]
    },
    phone:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    workStatus:{
        type:String
    },
    interests:{
        type:Array,
        default:[]
    },
    portfolio:{
        type:Array,
        default:[]
    },
    courses:{
        type:Array,
        default:[]
    },
    skills:{
        type:Array,
        default:[]
    },
    skillQuizz:{
        type:Array,
        default:[]
    }

},{timestamps:true})

export default mongoose.model("User",UserSchema)